[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/prediction/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "/index.html"
  status = 200
